### ISSUE TITLE
Inconsistencias leves en los decimales del experimento : Superficie Libre -> Remanso -> Tramos Fijos

### ISSUE THREAD

**Issue by Carlosmicael** [SmartWaterNetwork/DHYCOB#10]
Hay una leve inconsistencia en los resultados arrojados de la migración del experimento solo difiere en la ultima decima y no se si será en este caso importante este pequeño inconveniente o como en los anteriores experimentos no habría ningún problema en dichos resultados estarían correctamente a continuación adjunto las capturas de los experimentos.

NOTA: los resultados que difieren son desde la distancia -100 todos para abajo

EXPERIMENTO ORIGINAL:

![image](https://github.com/SmartWaterNetwork/DHYCOB/assets/116389799/ca2d9d3e-eef4-4f08-b6a2-ffdc476e2943)

EXPERIMENTO MIGRADO:

![image](https://github.com/SmartWaterNetwork/DHYCOB/assets/116389799/93544827-a438-46df-bfb6-47f6737d6836)

**Comment by lsantiago** [comment]
@HolgerBenavides su ayuda con retroalimentación sobre este caso. Gracias.

**Comment by HolgerBenavides** [comment]
Gracias. Dado que las variaciones son mínimas, se puede dar por válido.
