### ISSUE TITLE
Error Número de Froude (F) Experimento ->Superficie Libre->Tirante critico->Sección Circular

### ISSUE THREAD

**Issue by Carlosmicael** [SmartWaterNetwork/DHYCOB#3]
En el experimento original el Número de Froude (F) da 1 y en h canales da 1.000 habrá algún problema en el calculo es solo redondeo no estoy muy seguro  la verdad aquí adjunto la captura del experimento del laboratorio original y la herramienta Hcanales:

![image](https://github.com/SmartWaterNetwork/DHYCOB/assets/116389799/6d3608ed-8b20-4008-a2b0-8535627843b7)

Este mismo experimento migraron los chicos y el Número de Froude (F) da igual =1:

![image](https://github.com/SmartWaterNetwork/DHYCOB/assets/116389799/c177f17d-7fee-4274-8098-4b16b27f5e26)

**Comment by lsantiago** [comment]
@Carlosmicael La "," que se utiliza en 1 es el separador de decimales, considero que está bien el resultado. 

![image](https://github.com/SmartWaterNetwork/DHYCOB/assets/37159/ba84f000-646f-441e-aad2-806f8dce4be2)

**Comment by HolgerBenavides** [comment]
Correcto. Ambos valores son 1.
El uno se muestra con 3 decimales (1.000). Se podría reducir el número de decimales para no motivar el error (suponer que es mil).
