### ISSUE TITLE
Error Decimales Experimento-> Superficie Libre -> Salto Hidráulico ->Sección rectangular

### ISSUE THREAD

**Issue by Carlosmicael** [SmartWaterNetwork/DHYCOB#4]
Hay unos breves errores de redondeo de decimales en todos los resultados de este experimento en el dhycob la pagina original los decimales no son iguales a los de Hcanales no se si esto afectara a la precisión del calculo o no es relevante además el dhycob la pagina original tiene una opción que Hcanales no tiene no se si será importante pero lo quería recalcar imagen descriptiva:

![image](https://github.com/SmartWaterNetwork/DHYCOB/assets/116389799/61f4a823-3d96-40a7-8ebc-510df706b057)

**Comment by lsantiago** [comment]
@HolgerBenavides nos ayuda con su retroalimentación

**Comment by HolgerBenavides** [comment]
Cordial saludo.
Gracias por vuestro avance y por sus observaciones.

Si bien los resultados del experimento en DHYCOB son semejantes hasta el tercer decimal con los presentados por HCANALES, se dan por válidos. Aunque, siempre será mucho mejor enmendar el error.

![image](https://github.com/SmartWaterNetwork/DHYCOB/assets/113537783/cfc16a7b-c375-48fe-9c16-ac04ed0d40e3)

**Comment by HolgerBenavides** [comment]
Ciertamente, la pendiente no se debería presentar como un resultado, dado que en el régimen crítico la pendiente no forma parte del modelo primitivo.
